language: node_js
install: npm install
cache:
  directories:
  - node_modules
rvm:
- jruby-19mode
notifications:
  email:
  - tech@amicushq.com
  campfire:
    rooms:
      secure: jymulcRoRGgKJoLLEiAA6aQKuY0pJdaH792dUuo/eu1uAbDVmkV1oQl+jpD58rsHW4QFU9+TKcZKsdCHWHf8cm0S4CXiPpE4ztDaRqHRj1jdUbZFnoFpWJscyVJ5mWRrW2dQPym5/6JQTAzxscPOSG+zJlLEPfll740wnVkm2qs=
branches:
  only:
  - master
  - production
before_script:
  # http://stackoverflow.com/questions/16638573/auto-authorize-ssh-auth-requests-on-travis-ci
  # to make npm install not hang
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install -g grunt-cli
script:
  - grunt test