markdown: redcarpet
pygments: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
  render_options:
      - with_toc_data
      - hard_wrap