var Parser = require("./parser")
  , AttributeReaction = require("./reactions/attribute")
  , CollectionReaction = require("./reactions/collection")
  , ModelReaction = require("./reactions/model")
  , VariableReaction = require("./reactions/variable")
  , ConditionalReaction = require("./reactions/conditional")
  , PartialReaction = require("./reactions/partial")
  , ViewReaction = require("./reactions/view")
  , ScopeReaction = require("./reactions/scope")
  , path = require("path")

Parser.registerReaction(PartialReaction)
Parser.registerReaction(ScopeReaction)
Parser.registerReaction(AttributeReaction)
Parser.registerReaction(CollectionReaction)
Parser.registerReaction(ModelReaction)
Parser.registerReaction(VariableReaction)
Parser.registerReaction(ConditionalReaction)
Parser.registerReaction(ViewReaction)

module.exports = Parser
