var Parser = require("./parser")
  , AttributeReaction = require("./reactions/attribute")
  , CollectionReaction = require("./reactions/collection")
  , ModelReaction = require("./reactions/model")
  , VariableReaction = require("./reactions/variable")
  , ConditionalReaction = require("./reactions/conditional")
  , ContentPartialReaction = require("./reactions/content_partials")
  , ViewReaction = require("./reactions/views")
  , ScopeReaction = require("./reactions/scope")

Parser.registerReaction(ContentPartialReaction)
Parser.registerReaction(ScopeReaction)
Parser.registerReaction(AttributeReaction)
Parser.registerReaction(CollectionReaction)
Parser.registerReaction(ModelReaction)
Parser.registerReaction(VariableReaction)
Parser.registerReaction(ConditionalReaction)
Parser.registerReaction(ViewReaction)

module.exports = Parser
